<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\FlightStreamDeck.Core\EnumConverter.cs" Link="EnumConverter.cs" />
    <Compile Include="..\FlightStreamDeck.Core\EventValueLibrary.cs" Link="EventValueLibrary.cs" />
    <Compile Include="..\FlightStreamDeck.Core\TOGGLE_EVENT.cs" Link="TOGGLE_EVENT.cs" />
    <Compile Include="..\FlightStreamDeck.Core\TOGGLE_VALUE.cs" Link="TOGGLE_VALUE.cs" />
    <Compile Include="..\FlightStreamDeck.Logics\IFlightConnector.cs" Link="IFlightConnector.cs" />
    <Compile Include="..\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs" Link="SimConnectFlightConnector.cs" />
    <Compile Include="..\FlightStreamDeck.SimConnectFSX\Structs.cs" Link="Structs.cs" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />

    <Reference Include="Microsoft.FlightSimulator.SimConnect">
      <HintPath>$(MSFS_SDK)\SimConnect SDK\lib\managed\Microsoft.FlightSimulator.SimConnect.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
